# Generated by Django 2.2.12 on 2020-04-26 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
